title:              COMMAND SPACE LABATORY
email:              commandspacelab@gmail.com
description:        Knowledge Connectivity
author:             CMDS
baseurl:            "/"
url:                "https://blog.cmdspace.org"
timezone: Asia/Seoul
#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tag/

# Social Profiles
twitter_username:   
github_username:    commandspacelab
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   #UA-XXXXXXXXX-X # out your google-analytics code

#kakao
#defaults:
#  - scope:
#    path: ""
#    type: posts
#  value:
#    use_kakao-sdk: true
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
asset_url: /assets
comments:
  provider: "disqus"
  disqus:
    shortname : "command-space-lab"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-youtube